# Generated by Django 4.2.14 on 2024-07-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
